spring.application.name=made-by-her-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/made_by_her
spring.datasource.username=ajaysinghrajput
spring.datasource.password=s

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# JWT - CHANGE THIS IN PRODUCTION
app.jwt.secret=MadeByHerSuperSecretKeyForDevelopmentOnlyChangeMe123456789
app.jwt.expiration-ms=86400000

# Current business rule: one Village Partner can manage up to 5 women.
app.partner.max-women=5

# CORS for React frontend
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173
